### ISSUE TITLE
无法拖动文件到应用图标打开文件，如果有简单的文件后缀名识别更好了

### ISSUE THREAD

**Issue by Delay-n-days** [Sammy-T/gotepad#57]
无法拖动文件到应用图标打开文件，如果有简单的文件后缀名识别更好了

**Comment by Sammy-T** [comment]
I hope I'm not missing anything from the translation. But opening files by dragging them into the application is something I can look into.

**Comment by Sammy-T** [comment]
So I've played around a little with the frontend's drag and drop functionality but, so far, I don't have a reliable way of getting the full file path from the drop event.
